// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3mFOPYbjpfgirVFt_y3atg0RABRRGgd0',
    appId: '1:1074776985741:web:50ad1029a553a15644d2c4',
    messagingSenderId: '1074776985741',
    projectId: 'instalive-291d9',
    authDomain: 'instalive-291d9.firebaseapp.com',
    storageBucket: 'instalive-291d9.firebasestorage.app',
    measurementId: 'G-FGDSJ0XQE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACnboig54WtnpsDc8nOKVkUkZOs08Kblo',
    appId: '1:1074776985741:android:5dc1fb550e2988f544d2c4',
    messagingSenderId: '1074776985741',
    projectId: 'instalive-291d9',
    storageBucket: 'instalive-291d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHhl6Xq6Lcd8SlfZTZSXx6YtuGqyxBw4',
    appId: '1:1074776985741:ios:1bc912a1d2b2ce2144d2c4',
    messagingSenderId: '1074776985741',
    projectId: 'instalive-291d9',
    storageBucket: 'instalive-291d9.firebasestorage.app',
    iosClientId: '1074776985741-jbeempo98ep3gdl0sobv1dbimo2br4fh.apps.googleusercontent.com',
    iosBundleId: 'com.example.erronLiveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEHhl6Xq6Lcd8SlfZTZSXx6YtuGqyxBw4',
    appId: '1:1074776985741:ios:1bc912a1d2b2ce2144d2c4',
    messagingSenderId: '1074776985741',
    projectId: 'instalive-291d9',
    storageBucket: 'instalive-291d9.firebasestorage.app',
    iosClientId: '1074776985741-jbeempo98ep3gdl0sobv1dbimo2br4fh.apps.googleusercontent.com',
    iosBundleId: 'com.example.erronLiveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3mFOPYbjpfgirVFt_y3atg0RABRRGgd0',
    appId: '1:1074776985741:web:f4c957f86adab10644d2c4',
    messagingSenderId: '1074776985741',
    projectId: 'instalive-291d9',
    authDomain: 'instalive-291d9.firebaseapp.com',
    storageBucket: 'instalive-291d9.firebasestorage.app',
    measurementId: 'G-ZVSGWZV7JX',
  );
}
